# Generated by Django 3.0.8 on 2020-07-28 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qabot', '0002_auto_20200728_1446'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SimilarProblem',
            new_name='SimilarQuestion',
        ),
    ]
