# Generated by Django 3.0.8 on 2020-07-28 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qabot', '0003_auto_20200728_1449'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fqa',
            table='qabot_fqa',
        ),
    ]
