# Generated by Django 3.0.8 on 2020-07-28 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qabot', '0004_auto_20200728_1456'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fqa',
            table=None,
        ),
        migrations.AlterModelTable(
            name='similarquestion',
            table='qabot_similar_question',
        ),
    ]
