# Generated by Django 3.0.8 on 2020-07-31 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qabot', '0005_auto_20200728_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='FQA_COPY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField(max_length=500)),
                ('valid', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'qabot_fqa_copy1',
            },
        ),
        migrations.AlterField(
            model_name='similarquestion',
            name='fqa',
            field=models.ForeignKey(limit_choices_to={'valid': True}, on_delete=django.db.models.deletion.CASCADE, related_name='sq', to='qabot.FQA'),
        ),
    ]
